{"stats": {"errors": 0, "failures": 8, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 8}, "results": [{"classname": "index_test:TestSQLMoreQueries", "name": "test_select_all_dogs_names_in_alphabetical_order", "time": 0.0005156993865966797, "type": "failure", "errtype": "builtins.AssertionError", "message": "Lists differ: [] != [(None,), ('Clifford',), ('Lassie',), ('Li[73 chars]y',)]\n\nSecond list contains 9 additional elements.\nFirst extra element 0:\n(None,)\n\n- []\n+ [(None,),\n+  ('Clifford',),\n+  ('Lassie',),\n+  ('Little Ann',),\n+  ('McGruff',),\n+  ('Pickles',),\n+  ('Scooby',),\n+  ('Snoopy',),\n+  ('Snowy',)]", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/talum/sql-more-queries-lab-data-science/test/index_test.py\", line 23, in test_select_all_dogs_names_in_alphabetical_order\n    self.assertEqual(table.execute(select_all_dogs_names_in_alphabetical_order()).fetchall(), result)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: Lists differ: [] != [(None,), ('Clifford',), ('Lassie',), ('Li[73 chars]y',)]\n\nSecond list contains 9 additional elements.\nFirst extra element 0:\n(None,)\n\n- []\n+ [(None,),\n+  ('Clifford',),\n+  ('Lassie',),\n+  ('Little Ann',),\n+  ('McGruff',),\n+  ('Pickles',),\n+  ('Scooby',),\n+  ('Snoopy',),\n+  ('Snowy',)]\n"}, {"classname": "index_test:TestSQLMoreQueries", "name": "test_select_all_female_dogs_name_and_breed", "time": 0.0003769397735595703, "type": "failure", "errtype": "builtins.AssertionError", "message": "Lists differ: [] != [('Little Ann', 'coonhound'), ('Pickles', [56 chars]er')]\n\nSecond list contains 4 additional elements.\nFirst extra element 0:\n('Little Ann', 'coonhound')\n\n- []\n+ [('Little Ann', 'coonhound'),\n+  ('Pickles', 'black lab'),\n+  ('Lassie', 'collie'),\n+  ('Snowy', 'fox terrier')]", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/talum/sql-more-queries-lab-data-science/test/index_test.py\", line 19, in test_select_all_female_dogs_name_and_breed\n    self.assertEqual(table.execute(select_all_female_dogs_name_and_breed()).fetchall(), result)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: Lists differ: [] != [('Little Ann', 'coonhound'), ('Pickles', [56 chars]er')]\n\nSecond list contains 4 additional elements.\nFirst extra element 0:\n('Little Ann', 'coonhound')\n\n- []\n+ [('Little Ann', 'coonhound'),\n+  ('Pickles', 'black lab'),\n+  ('Lassie', 'collie'),\n+  ('Snowy', 'fox terrier')]\n"}, {"classname": "index_test:TestSQLMoreQueries", "name": "test_select_hungry_dogs_name_and_breed_ordered_by_youngest_to_oldest", "time": 0.0003604888916015625, "type": "failure", "errtype": "builtins.AssertionError", "message": "Lists differ: [] != [('Snoopy', 'beagle'), ('Clifford', 'big r[102 chars]ab')]\n\nSecond list contains 6 additional elements.\nFirst extra element 0:\n('Snoopy', 'beagle')\n\n- []\n+ [('Snoopy', 'beagle'),\n+  ('Clifford', 'big red'),\n+  (None, 'golden retriever'),\n+  ('Scooby', 'great dane'),\n+  ('Lassie', 'collie'),\n+  ('Pickles', 'black lab')]", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/talum/sql-more-queries-lab-data-science/test/index_test.py\", line 31, in test_select_hungry_dogs_name_and_breed_ordered_by_youngest_to_oldest\n    self.assertEqual(table.execute(select_hungry_dogs_name_and_breed_ordered_by_youngest_to_oldest()).fetchall(), result)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: Lists differ: [] != [('Snoopy', 'beagle'), ('Clifford', 'big r[102 chars]ab')]\n\nSecond list contains 6 additional elements.\nFirst extra element 0:\n('Snoopy', 'beagle')\n\n- []\n+ [('Snoopy', 'beagle'),\n+  ('Clifford', 'big red'),\n+  (None, 'golden retriever'),\n+  ('Scooby', 'great dane'),\n+  ('Lassie', 'collie'),\n+  ('Pickles', 'black lab')]\n"}, {"classname": "index_test:TestSQLMoreQueries", "name": "test_select_name_age_and_temperament_of_oldest_dog", "time": 0.0002105236053466797, "type": "failure", "errtype": "builtins.AssertionError", "message": "Lists differ: [] != [('Pickles', 13, 'mischievous')]\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n('Pickles', 13, 'mischievous')\n\n- []\n+ [('Pickles', 13, 'mischievous')]", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/talum/sql-more-queries-lab-data-science/test/index_test.py\", line 35, in test_select_name_age_and_temperament_of_oldest_dog\n    self.assertEqual(table.execute(select_name_age_and_temperament_of_oldest_dog()).fetchall(), result)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: Lists differ: [] != [('Pickles', 13, 'mischievous')]\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n('Pickles', 13, 'mischievous')\n\n- []\n+ [('Pickles', 13, 'mischievous')]\n"}, {"classname": "index_test:TestSQLMoreQueries", "name": "test_select_name_and_age_of_three_youngest_dogs", "time": 0.00021719932556152344, "type": "failure", "errtype": "builtins.AssertionError", "message": "Lists differ: [] != [('Snoopy', 3), ('Clifford', 4), (None, 4)]\n\nSecond list contains 3 additional elements.\nFirst extra element 0:\n('Snoopy', 3)\n\n- []\n+ [('Snoopy', 3), ('Clifford', 4), (None, 4)]", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/talum/sql-more-queries-lab-data-science/test/index_test.py\", line 39, in test_select_name_and_age_of_three_youngest_dogs\n    self.assertEqual(table.execute(select_name_and_age_of_three_youngest_dogs()).fetchall(), result)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: Lists differ: [] != [('Snoopy', 3), ('Clifford', 4), (None, 4)]\n\nSecond list contains 3 additional elements.\nFirst extra element 0:\n('Snoopy', 3)\n\n- []\n+ [('Snoopy', 3), ('Clifford', 4), (None, 4)]\n"}, {"classname": "index_test:TestSQLMoreQueries", "name": "test_select_name_and_breed_of_dogs_between_age_five_and_ten_ordered_by_oldest_to_youngest", "time": 0.0003285408020019531, "type": "failure", "errtype": "builtins.AssertionError", "message": "Lists differ: [] != [('McGruff', 'bloodhound'), ('Snowy', 'fox[83 chars]nd')]\n\nSecond list contains 5 additional elements.\nFirst extra element 0:\n('McGruff', 'bloodhound')\n\n- []\n+ [('McGruff', 'bloodhound'),\n+  ('Snowy', 'fox terrier'),\n+  ('Lassie', 'collie'),\n+  ('Scooby', 'great dane'),\n+  ('Little Ann', 'coonhound')]", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/talum/sql-more-queries-lab-data-science/test/index_test.py\", line 43, in test_select_name_and_breed_of_dogs_between_age_five_and_ten_ordered_by_oldest_to_youngest\n    self.assertEqual(table.execute(select_name_and_breed_of_dogs_between_age_five_and_ten_ordered_by_oldest_to_youngest()).fetchall(), result)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: Lists differ: [] != [('McGruff', 'bloodhound'), ('Snowy', 'fox[83 chars]nd')]\n\nSecond list contains 5 additional elements.\nFirst extra element 0:\n('McGruff', 'bloodhound')\n\n- []\n+ [('McGruff', 'bloodhound'),\n+  ('Snowy', 'fox terrier'),\n+  ('Lassie', 'collie'),\n+  ('Scooby', 'great dane'),\n+  ('Little Ann', 'coonhound')]\n"}, {"classname": "index_test:TestSQLMoreQueries", "name": "test_select_nameless_dog", "time": 0.00021910667419433594, "type": "failure", "errtype": "builtins.AssertionError", "message": "Lists differ: [] != [(9, None, 4, 'M', 'golden retriever', 'playful', 1)]\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n(9, None, 4, 'M', 'golden retriever', 'playful', 1)\n\n- []\n+ [(9, None, 4, 'M', 'golden retriever', 'playful', 1)]", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/talum/sql-more-queries-lab-data-science/test/index_test.py\", line 27, in test_select_nameless_dog\n    self.assertEqual(table.execute(select_nameless_dog()).fetchall(), result)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: Lists differ: [] != [(9, None, 4, 'M', 'golden retriever', 'playful', 1)]\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n(9, None, 4, 'M', 'golden retriever', 'playful', 1)\n\n- []\n+ [(9, None, 4, 'M', 'golden retriever', 'playful', 1)]\n"}, {"classname": "index_test:TestSQLMoreQueries", "name": "test_select_select_name_age_and_hungry_of_hungry_dogs_between_age_two_and_seven_in_alphabetical_order", "time": 0.00032806396484375, "type": "failure", "errtype": "builtins.AssertionError", "message": "Lists differ: [] != [(None, 4, 1), ('Clifford', 4, 1), ('Lassi[41 chars], 1)]\n\nSecond list contains 5 additional elements.\nFirst extra element 0:\n(None, 4, 1)\n\n- []\n+ [(None, 4, 1),\n+  ('Clifford', 4, 1),\n+  ('Lassie', 7, 1),\n+  ('Scooby', 6, 1),\n+  ('Snoopy', 3, 1)]", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/talum/sql-more-queries-lab-data-science/test/index_test.py\", line 47, in test_select_select_name_age_and_hungry_of_hungry_dogs_between_age_two_and_seven_in_alphabetical_order\n    self.assertEqual(table.execute(select_name_age_and_hungry_of_hungry_dogs_between_age_two_and_seven_in_alphabetical_order()).fetchall(), result)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n  File \"/opt/conda/envs/learn-env/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: Lists differ: [] != [(None, 4, 1), ('Clifford', 4, 1), ('Lassi[41 chars], 1)]\n\nSecond list contains 5 additional elements.\nFirst extra element 0:\n(None, 4, 1)\n\n- []\n+ [(None, 4, 1),\n+  ('Clifford', 4, 1),\n+  ('Lassie', 7, 1),\n+  ('Scooby', 6, 1),\n+  ('Snoopy', 3, 1)]\n"}]}